<?php
/**
 * Default editable Gutenberg content for the SoundShow comparison page.
 *
 * @package SonoRiva_Marketing
 */

if (!defined('ABSPATH')) {
    exit;
}

function sonoriva_marketing_soundshow_block_content(): string
{
    $theme_uri = esc_url(set_url_scheme(get_template_directory_uri(), 'https'));
    $home_url = esc_url(home_url('/'));

    return <<<HTML
<!-- wp:group {"align":"full","className":"comparison-hero","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull comparison-hero"><!-- wp:columns {"verticalAlignment":"center","align":"wide","className":"shell comparison-hero-grid"} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center shell comparison-hero-grid"><!-- wp:column {"verticalAlignment":"center","className":"comparison-hero-copy"} -->
<div class="wp-block-column is-vertically-aligned-center comparison-hero-copy"><!-- wp:paragraph {"className":"breadcrumbs"} -->
<p class="breadcrumbs"><a href="{$home_url}">Accueil</a><span>→</span><span>Alternative à SoundShow</span></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Alternative cloud à SoundShow</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Votre régie SoundShow.<br><em>Accessible dans le cloud.</em></h1><!-- /wp:heading -->
<!-- wp:paragraph --><p>SonoRiva est une régie son en ligne pour le théâtre et le spectacle vivant. Elle importe les projets <code>.ssp</code>, stocke les sons avec le spectacle et ouvre la régie depuis un navigateur.</p><!-- /wp:paragraph -->
<!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://app.sonoriva.fr/demo">Tester SonoRiva ↗</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#comparatif">Comparer les approches ↓</a></div><!-- /wp:button --></div><!-- /wp:buttons -->
<!-- wp:paragraph {"className":"comparison-disclaimer"} --><p class="comparison-disclaimer">SoundShow et SonoRiva sont deux produits indépendants. Cette page décrit leurs modes d’utilisation respectifs et les possibilités d’import disponibles dans SonoRiva.</p><!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"className":"product-shot comparison-hero-shot","layout":{"type":"constrained"}} --><div class="wp-block-group product-shot comparison-hero-shot"><!-- wp:html --><div class="product-shot-bar" aria-hidden="true"><span><i></i><i></i><i></i></span><strong>SonoRiva dans le navigateur</strong><em>Capture réelle</em></div><!-- /wp:html --><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"product-shot-crop product-shot-crop-comparison"} --><figure class="wp-block-image size-full product-shot-crop product-shot-crop-comparison"><img src="{$theme_uri}/assets/images/app-dashboard.png" alt="Soundboard de la régie son cloud SonoRiva dans un navigateur" width="1600" height="1050"/></figure><!-- /wp:image --></div><!-- /wp:group --></div><!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","className":"comparison-intro section","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull comparison-intro section"><!-- wp:columns {"align":"wide","className":"shell comparison-intro-grid"} --><div class="wp-block-columns alignwide shell comparison-intro-grid"><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Ce que change le cloud</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Le spectacle n’est plus lié à une seule installation.</h2><!-- /wp:heading --></div><!-- /wp:column -->
<!-- wp:column {"className":"comparison-benefits"} --><div class="wp-block-column comparison-benefits"><!-- wp:group --><div class="wp-block-group"><!-- wp:paragraph {"className":"sr-index"} --><p class="sr-index">01</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Projet associé au compte</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Les catégories, réglages et médias du spectacle sont enregistrés dans SonoRiva et retrouvés après connexion.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group --><div class="wp-block-group"><!-- wp:paragraph {"className":"sr-index"} --><p class="sr-index">02</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Ouverture dans le navigateur</h3><!-- /wp:heading --><!-- wp:paragraph --><p>La régie web fonctionne sans installation initiale et peut aussi être installée comme PWA.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group --><div class="wp-block-group"><!-- wp:paragraph {"className":"sr-index"} --><p class="sr-index">03</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Lecture hors ligne</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Les catégories choisies peuvent être chargées sur l’appareil pour une lecture locale sans connexion réseau.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group --><div class="wp-block-group"><!-- wp:paragraph {"className":"sr-index"} --><p class="sr-index">04</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Multi-sorties avec Bridge</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Sur macOS et Windows, SonoRiva Bridge relie l’interface cloud aux sorties audio physiques de la régie.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"anchor":"comparatif","align":"full","className":"comparison-table-section section","layout":{"type":"constrained"}} -->
<div id="comparatif" class="wp-block-group alignfull comparison-table-section section"><!-- wp:group {"className":"shell","layout":{"type":"constrained"}} --><div class="wp-block-group shell"><!-- wp:group {"className":"section-heading centered","layout":{"type":"constrained"}} --><div class="wp-block-group section-heading centered"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">SoundShow ou SonoRiva</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Deux régies visuelles.<br>Deux architectures différentes.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>SoundShow est une application de bureau pour Windows, macOS et Linux. SonoRiva place les projets dans une application web, avec un composant desktop uniquement pour les sorties audio avancées.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:table {"className":"comparison-table-wrap"} --><figure class="wp-block-table comparison-table-wrap"><table><thead><tr><th>Usage</th><th>SoundShow</th><th>SonoRiva</th></tr></thead><tbody><tr><th>Accès à la régie</th><td>Application installée sur Windows, macOS ou Linux</td><td>Application web dans le navigateur et PWA</td></tr><tr><th>Emplacement du projet</th><td>Fichier de projet exportable ou transférable</td><td>Projet et médias associés au compte cloud</td></tr><tr><th>Recherche de sons</th><td>Recherche et ajout intégrés</td><td>Recherche Openverse, préécoute, filtres, attribution et ajout intégrés</td></tr><tr><th>Lecture simultanée</th><td>Plusieurs lecteurs et instances</td><td>Plusieurs lectures actives dans la colonne de régie</td></tr><tr><th>Sorties audio</th><td>Routage depuis l’application de bureau</td><td>Routage coloré par son avec SonoRiva Bridge</td></tr><tr><th>Utilisation sans Internet</th><td>Projet et médias locaux</td><td>Catégories chargées localement dans la PWA</td></tr><tr><th>Passage vers SonoRiva</th><td>Export du projet <code>.ssp</code></td><td>Import du <code>.ssp</code> et des médias associés</td></tr></tbody></table></figure><!-- /wp:table -->
<!-- wp:paragraph {"className":"comparison-source-note"} --><p class="comparison-source-note">Comparaison fonctionnelle fondée sur les informations publiques de SoundShow et sur la version actuelle de SonoRiva. Les fonctions des deux logiciels peuvent évoluer.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","className":"migration-section section","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull migration-section section"><!-- wp:columns {"align":"wide","className":"shell migration-grid"} --><div class="wp-block-columns alignwide shell migration-grid"><!-- wp:column {"className":"migration-copy"} --><div class="wp-block-column migration-copy"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Import SoundShow</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Le fichier <code>.ssp</code> devient un projet cloud.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>L’import analyse le projet, recherche les médias disponibles et recrée les éléments audio compatibles dans un nouveau spectacle SonoRiva.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"inline-link"} --><p class="inline-link"><a href="https://app.sonoriva.fr/docs/guides/importer-des-sons">Voir le fonctionnement de l’import ↗</a></p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:list {"ordered":true,"className":"migration-steps"} --><ol class="wp-block-list migration-steps"><li><strong>Sélection du dossier</strong><br>SonoRiva repère le fichier <code>.ssp</code>, ses sous-dossiers et les médias audio présents.</li><li><strong>Analyse avant import</strong><br>L’écran récapitule les catégories, les fichiers locaux, les sources distantes reconnues et les médias manquants.</li><li><strong>Création du spectacle</strong><br>Les catégories, couleurs, boucles, points d’entrée et de sortie, fondus et métadonnées compatibles sont recréés.</li></ol><!-- /wp:list --></div><!-- /wp:column --></div><!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","className":"migration-scope section","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull migration-scope section"><!-- wp:columns {"align":"wide","className":"shell migration-scope-grid"} --><div class="wp-block-columns alignwide shell migration-scope-grid"><!-- wp:column {"className":"migration-scope-card"} --><div class="wp-block-column migration-scope-card"><!-- wp:paragraph {"className":"card-kicker"} --><p class="card-kicker">Repris par l’import</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">La structure audio utile à la régie.</h2><!-- /wp:heading --><!-- wp:list {"className":"check-list"} --><ul class="wp-block-list check-list"><li>Catégories et ordre des sons</li><li>Couleurs et titres</li><li>Points de début et de fin</li><li>Boucles et fondus</li><li>Fichiers locaux retrouvés</li><li>Sources distantes compatibles</li></ul><!-- /wp:list --></div><!-- /wp:column -->
<!-- wp:column {"className":"migration-scope-card"} --><div class="wp-block-column migration-scope-card"><!-- wp:paragraph {"className":"card-kicker"} --><p class="card-kicker">Périmètre</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Un import centré sur le son.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>SonoRiva ne reproduit pas les modules vidéo, éclairage, MIDI, Stream Deck ou effets audio de SoundShow. Les éléments absents ou non compatibles sont signalés pendant l’analyse et restent à compléter séparément.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","className":"faq-section section","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull faq-section section"><!-- wp:columns {"align":"wide","className":"shell faq-grid"} --><div class="wp-block-columns alignwide shell faq-grid"><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Questions sur la migration</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Passer de SoundShow à SonoRiva.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>L’import peut être testé depuis la démo ou depuis un espace SonoRiva.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"className":"faq-list"} --><div class="wp-block-column faq-list"><!-- wp:details --><details class="wp-block-details"><summary>SonoRiva remplace-t-il entièrement SoundShow&nbsp;?</summary><!-- wp:paragraph --><p>Les deux applications couvrent la lecture et l’organisation de sons, mais leur périmètre diffère. SonoRiva se concentre sur la régie audio cloud, le fonctionnement dans le navigateur, le hors-ligne et le routage avec Bridge.</p><!-- /wp:paragraph --></details><!-- /wp:details --><!-- wp:details --><details class="wp-block-details"><summary>Faut-il envoyer tous les sons un par un&nbsp;?</summary><!-- wp:paragraph --><p>Non. La sélection d’un dossier permet d’analyser ensemble le fichier <code>.ssp</code>, les sous-dossiers et les médias disponibles.</p><!-- /wp:paragraph --></details><!-- /wp:details --><!-- wp:details --><details class="wp-block-details"><summary>Que deviennent les sons distants du projet&nbsp;?</summary><!-- wp:paragraph --><p>Les sources distantes compatibles sont reconnues pendant l’analyse. Leur disponibilité et leur licence sont conservées dans les informations du son importé.</p><!-- /wp:paragraph --></details><!-- /wp:details --><!-- wp:details --><details class="wp-block-details"><summary>Le spectacle fonctionne-t-il ensuite hors ligne&nbsp;?</summary><!-- wp:paragraph --><p>Oui. Après l’import, les catégories nécessaires peuvent être rendues disponibles hors ligne depuis SonoRiva.</p><!-- /wp:paragraph --></details><!-- /wp:details --></div><!-- /wp:column --></div><!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","className":"final-cta","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull final-cta"><!-- wp:group {"className":"shell final-cta-inner","layout":{"type":"constrained"}} --><div class="wp-block-group shell final-cta-inner"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Test sans compte</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Ouvrez la régie cloud.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>La démo donne accès au vrai soundboard, à la recherche Openverse et aux réglages des sons.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://app.sonoriva.fr/demo">Tester SonoRiva ↗</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="{$home_url}#fonctionnalites">Voir toutes les fonctionnalités</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div>
<!-- /wp:group -->
HTML;
}
